"""update user table , notifications, compost training

Revision ID: 01a6391033f6
Revises: 
Create Date: 2025-03-02 17:47:54.950469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01a6391033f6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('push_token', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('device_type', sa.String(length=20), nullable=True))

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('channel', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('delivery_status', sa.String(length=20), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('last_login', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('last_login')
        batch_op.drop_column('phone')

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_column('delivery_status')
        batch_op.drop_column('channel')

    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.drop_column('device_type')
        batch_op.drop_column('push_token')

    # ### end Alembic commands ###
