"""added wifi connected field in device table

Revision ID: 1e888c959f88
Revises: b18961674065
Create Date: 2025-03-05 06:10:38.691632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e888c959f88'
down_revision = 'b18961674065'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wifi_connected', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.drop_column('wifi_connected')

    # ### end Alembic commands ###
