"""added alert evel for notification tables

Revision ID: 2f34b6f3d23a
Revises: afa13237f617
Create Date: 2025-04-04 02:01:11.918788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f34b6f3d23a'
down_revision = 'afa13237f617'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('compost_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ph', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('oxygen_level', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('carbon_nitrogen_ratio', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('nitrogen_content', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('potassium_content', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('phosphorus_content', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('compost_data', schema=None) as batch_op:
        batch_op.drop_column('phosphorus_content')
        batch_op.drop_column('potassium_content')
        batch_op.drop_column('nitrogen_content')
        batch_op.drop_column('carbon_nitrogen_ratio')
        batch_op.drop_column('oxygen_level')
        batch_op.drop_column('ph')

    # ### end Alembic commands ###
