"""added is_online column to device table

Revision ID: 445b70436a24
Revises: 7568cec9a484
Create Date: 2025-04-04 01:44:04.493823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '445b70436a24'
down_revision = '7568cec9a484'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_online', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.drop_column('is_online')

    # ### end Alembic commands ###
