"""added alert evel for notification tables colm

Revision ID: af8120240abd
Revises: 2f34b6f3d23a
Create Date: 2025-04-04 02:06:30.044074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af8120240abd'
down_revision = '2f34b6f3d23a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('registered_on', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.drop_column('registered_on')

    # ### end Alembic commands ###
