"""updated Device Table

Revision ID: e1719a140ac3
Revises: 5d89ddb631c7
Create Date: 2025-03-02 19:51:50.077321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1719a140ac3'
down_revision = '5d89ddb631c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('browser', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('os', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('location_city', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('location_region', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('location_country', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.drop_column('location_country')
        batch_op.drop_column('location_region')
        batch_op.drop_column('location_city')
        batch_op.drop_column('os')
        batch_op.drop_column('browser')

    # ### end Alembic commands ###
